# -*- coding: utf-8 -*-
"""Analisis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11BQix9s2RRZeGBFk17DLR7WBjntlEr40

1. Pre Requsitos | librerias requeridas
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns # Para graficación
from sklearn.cluster import KMeans # Para el modelamiento

"""2. Carga de Datos extraidos"""

# Ubicacion del archivo de datos
url = '/content/drive/MyDrive/Colab Notebooks/movies.csv' # external url?

# Se carga el archvio csv con pandas DataFrame
data = pd.read_csv(url) # Recupera los datos en formato csv a tipo dataframe (Estructura de datos bidimensional)
data.head() # Visualiza los 5 primeros datos del dataframe
data

"""3. Inspeccion de la Data"""

# Remove unnecesary cols
data = data.drop(data.columns[[0]],axis = 1)
data = data.drop(data.columns[[0]],axis = 1)

data.info()

#Conversion de tipos de datos para analisis
data["Recaudación ($USD)[2]"]=data["Recaudación ($USD)[2]"].str.replace(",", ".")
data["Recaudación ($USD)[2]"]=data["Recaudación ($USD)[2]"].str.replace(".", "")

data["Recaudación ($MXN)"]=data["Recaudación ($MXN)"].str.replace(",", ".")
data["Recaudación ($MXN)"]=data["Recaudación ($MXN)"].str.replace(".", "")

data["Recaudación ($USD)[2]"] = data["Recaudación ($USD)[2]"].astype(float)
data["Recaudación ($MXN)"] = data["Recaudación ($MXN)"].astype(float)

data.info()

data.describe()

"""4. Analisis de la data"""

#Matriz de correlacion
corr = data.corr()
corr

sns.pairplot(data,hue="Asistentes (Millones)")

sel_data = data[['Recaudación ($USD)[2]', 'Asistentes (Millones)']]
sel_data

def plot_dispersion(x, figure_name, max_k = 10, n_init = 10):
    inertia = []

    for k in range(1, max_k):
        kmeans = KMeans(n_clusters = k, n_init = n_init).fit(x)
        inertia.append(kmeans.inertia_)

    plt.plot(range(1, max_k), inertia, 'bx-')
    plt.xlabel('k')
    plt.ylabel(u'Dispersión')
    plt.title(figure_name)

plot_dispersion(sel_data, 'Dispersion')